### ISSUE TITLE
Niklas Review

### ISSUE THREAD

**Issue by Blinningjr** [Decending/D7020E_exam#1]
Looks good, I only have one minor suggestion.

You could use wrapping sub for calculating execution time to avoid the bug that happens when start > end.
https://github.com/Decending/D7020E_exam/blob/5154bfd2ebd3f95c7a8fc858a48afe7d0327a4f9/src/common.rs#L80

**Comment by Decending** [comment]
I've addressed this issue now, please confirm that it is solved.
