### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rubenasplund** [Decending/D7020E_exam#2]
Good job, it looks good!

As Niklas said you can use wrapping sub for calculating start and end in these places also (line 88, 119, 146, 153, 157):

https://github.com/Decending/D7020E_exam/blob/main/src/common.rs#L88

https://github.com/Decending/D7020E_exam/blob/main/src/common.rs#L119

https://github.com/Decending/D7020E_exam/blob/main/src/common.rs#L146

https://github.com/Decending/D7020E_exam/blob/main/src/common.rs#L153

https://github.com/Decending/D7020E_exam/blob/main/src/common.rs#L157

**Comment by Decending** [comment]
I've addressed these issues, please confirm that the issue is solved.
