### ISSUE TITLE
Preemption

### ISSUE THREAD

**Issue by rubenasplund** [Decending/D7020E_exam#3]
The preemption_revisited() function seems not to be working correctly. It returns 70, 60, 0.

T1 | 80 | 10 | 0 | 70
-- | -- | -- | -- | --
T2 | 90 | 30 | 0 | 60
T3 | 34 | 30 | 4 | 0

It should return 90, 60, 0.

T1 | 100 | 10 | 0 | 90
-- | -- | -- | -- | --
T2 | 90 | 30 | 0 | 60
T3 | 34 | 30 | 4 | 0

**Comment by Decending** [comment]
I have uploaded a new version of it, check the newest upload
